resolver 10.89.0.1 valid=15s ipv6=off;

location / {
    index index.html;
    try_files $uri $uri/ /index.html;
}

location /api/web/ {
    rewrite ^/api/web/(.*)$ /$1 break;
    proxy_pass http://web-apis:5000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    send_timeout 300s;
}

location /api/proxmox/ {
    rewrite ^/api/proxmox/(.*)$ /$1 break;
    proxy_pass http://proxmox-apis:5001;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    send_timeout 300s;
}